version: 2
jobs:
  build:
    working_directory: ~/withPerm
    docker:
      - image: circleci/node:8.4.0
    branches:
      only:
        - master
        - /v-.*/
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - run:
          name: test:suite
          command: npm run test:suite
      - run:
          name: codecov
          command: bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: ./coverage
          prefix: coverage
